
CREATE DATABASE `CLEANERS_MANAGEMENT`;



USE `CLEANERS_MANAGEMENT`;

CREATE TABLE `DIARIST`(
ID INT NOT NULL AUTO_INCREMENT,
CPF VARCHAR(11),
`NAME` VARCHAR(100),
PRIMARY KEY (ID));

CREATE TABLE `RESPONSIBLE`(
`NAME` VARCHAR(100),
CPF VARCHAR(11),
PRIMARY KEY(CPF)
);

CREATE TABLE HOUSE_TYPE(
ID INT PRIMARY KEY AUTO_INCREMENT ,
SIZE ENUM('P','M','G'),
PRICE NUMERIC(5,2));

CREATE TABLE `RESIDENCY`(
ID INT PRIMARY KEY AUTO_INCREMENT,
RESPONSIBLE_CPF VARCHAR(11),
CITY VARCHAR(50) NOT NULL,
DISTRICT VARCHAR(50) NOT NULL,
STREET VARCHAR(50) NOT NULL,
COMPLEMENT VARCHAR(100) NOT NULL,
HOUSE_NUMBER INT NOT NULL,
HOUSE_ID INT,
FOREIGN KEY(RESPONSIBLE_CPF) REFERENCES `RESPONSIBLE`(CPF),
FOREIGN KEY(HOUSE_ID) REFERENCES `HOUSE_TYPE`(ID)
);

CREATE TABLE `SCHEDULING`(
ID INT PRIMARY KEY AUTO_INCREMENT,
`DATE` DATETIME,
CLEANER_ID INT,
RESIDENCY_ID INT,
FOREIGN KEY(RESIDENCY_ID) REFERENCES `RESIDENCY`(ID),
FOREIGN KEY(CLEANER_ID) REFERENCES `DIARIST`(ID)
); 

CREATE TABLE `WORK_DONE`(
WORK_ID INT PRIMARY KEY auto_increment,
SCHEDULE_ID INT,
JOB_REALIZED ENUM('Y','N'),
PAYMENT ENUM('Y','N'),
RATE INT(10),
RATE_MESSAGE VARCHAR(255),
FOREIGN KEY(SCHEDULE_ID) REFERENCES `SCHEDULING`(ID)
); 